eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

server:
  port: 8093
spring:
  application:
    name: app-mayikt-zuul
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_gateway?useUnicode=true&characterEncoding=UTF-8
zuul:
  routes:
    api-a:
      path: /api-weixin/**
      serviceId: app-mayikt-weixin
    api-b:
      path: /api-member/**
      serviceId: app-mayikt-member
